name: Verify Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: markdown-link-check
      uses: gaurav-nelson/github-action-markdown-link-check@1.0.3
    
    - name: Spellcheck Action
      uses: rojopolis/spellcheck-github-actions@0.5.0
