name: Verify Documentation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - name: markdown-link-check
      uses: gaurav-nelson/github-action-markdown-link-check@1.0.3
      
  spellcheck:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        experimental: [true]
    continue-on-error: true
    steps:
    - name: Spellcheck Action
      uses: rojopolis/spellcheck-github-actions@0.5.0
