name: Verify Documentation

on: [push, pull_request]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v2
    - name: markdown-link-check
      uses: gaurav-nelson/github-action-markdown-link-check@1.0.13
      
  spellcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Spellcheck Action
      uses: rojopolis/spellcheck-github-actions@0.20.0
